### ISSUE TITLE
add a personified logo

### ISSUE THREAD

**Issue by Shreyalytical** [AmreshSinha/glassFolio#12]
a personified logo is your signature on your portfolio website. I'd like to create a logo and add changes.

**Comment by AmreshSinha** [comment]
Can you share some examples of logo which you have designed for this?

**Comment by Shreyalytical** [comment]
I've not yet designed but I'll add screenshots if you want in the evening, does that work?

**Comment by Shreyalytical** [comment]
I mean I'll design and add screenshots!

**Comment by AmreshSinha** [comment]
Sure :+1:

**Comment by AmreshSinha** [comment]
can you create a 956x170 dimension logo?
with format like:
</glassFolio> 
(if text goes beyond 956 then you can increase width :heavy_check_mark: )

**Comment by AmreshSinha** [comment]
> yes a written logo with that dimension works just fine. kindly assign the task to me and please , suggest that should i send the screenshot for the logo again or should add a PR

lets discuss here first about the logo then pr :)

**Comment by Shreyalytical** [comment]
![Untitled design](https://user-images.githubusercontent.com/79441201/136695548-eda30934-5525-4fbe-8fa8-4c4ea78f31ff.png)

here are your design choices that i have worked upon , you  can choose any of these or can suggest some changes in any one that you like. 👍

**Comment by Shreyalytical** [comment]
alright thanks

**Comment by AmreshSinha** [comment]
Yeah, my bad! I was busy with my college work. Will review and merge it :+1:
