### ISSUE TITLE
Add a contact pop-up modal with a form for clients to request your services

### ISSUE THREAD

**Issue by aswinikalyan30** [AmreshSinha/glassFolio#19]

**Comment by aswinikalyan30** [comment]
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/76677408/194849250-8130304e-f0c2-4b07-9edf-348ff54d6b7f.png">
Something like this, i will improve the css to glassmorphism

**Comment by aswinikalyan30** [comment]
Hey, any updates on this?

**Comment by AmreshSinha** [comment]
Well yeah, this recent one feels much better than the old pr which you created. Also, make sure the contrast is okay.

**Comment by aswinikalyan30** [comment]
Sure

**Comment by aswinikalyan30** [comment]
Updated it, could u review it?

**Comment by aswinikalyan30** [comment]
Hi could you review the PR?

**Comment by aswinikalyan30** [comment]
Hey, could you review it? with hacktoberfest coming to an end, itll be great if you could either accept/reject the PR
